import type { User, Project, Sprint, UserStory, Task, Issue, Epic } from "../types";

// Acme Web Users with enhanced profiles
export const acmeUsers: User[] = [
  {
    id: "acme-1",
    name: "Jennifer Martinez",
    email: "jennifer@acmeweb.com",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
    role: "Product Owner",
    skills: ["Product Strategy", "User Research", "Roadmapping", "Stakeholder Management"],
    hoursPerWeek: 40,
    historicalVelocity: 35,
  },
  {
    id: "acme-2",
    name: "Robert Chen",
    email: "robert@acmeweb.com",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400",
    role: "Scrum Master",
    skills: ["Agile Coaching", "Facilitation", "Process Improvement", "Metrics"],
    hoursPerWeek: 40,
    historicalVelocity: 32,
  },
  {
    id: "acme-3",
    name: "Priya Patel",
    email: "priya@acmeweb.com",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    role: "Developer",
    skills: ["React", "TypeScript", "Node.js", "GraphQL", "AWS"],
    hoursPerWeek: 40,
    historicalVelocity: 28,
  },
  {
    id: "acme-4",
    name: "Marcus Johnson",
    email: "marcus@acmeweb.com",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    role: "Developer",
    skills: ["Python", "Django", "PostgreSQL", "Docker", "Redis"],
    hoursPerWeek: 40,
    historicalVelocity: 30,
  },
  {
    id: "acme-5",
    name: "Sarah Kim",
    email: "sarah@acmeweb.com",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
    role: "Developer",
    skills: ["Vue.js", "JavaScript", "REST APIs", "MongoDB", "CI/CD"],
    hoursPerWeek: 32,
    historicalVelocity: 24,
  },
  {
    id: "acme-6",
    name: "James Wilson",
    email: "james@acmeweb.com",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    role: "Developer",
    skills: ["Java", "Spring Boot", "Microservices", "Kubernetes", "MySQL"],
    hoursPerWeek: 40,
    historicalVelocity: 26,
  },
  {
    id: "acme-7",
    name: "Lisa Anderson",
    email: "lisa@acmeweb.com",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400",
    role: "QA",
    skills: ["Test Automation", "Selenium", "Jest", "Cypress", "QA Strategy"],
    hoursPerWeek: 40,
    historicalVelocity: 22,
  },
  {
    id: "acme-8",
    name: "David Lee",
    email: "david@acmeweb.com",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
    role: "QA",
    skills: ["Manual Testing", "Bug Tracking", "API Testing", "Performance Testing"],
    hoursPerWeek: 40,
    historicalVelocity: 20,
  },
];

// Acme Web Project
export const acmeProject: Project = {
  id: "acme-web",
  name: "Acme Web",
  description: "Next-generation web platform for Acme Corporation with advanced features and scalability",
  color: "#8B5CF6",
  members: acmeUsers,
  createdAt: new Date("2025-09-01"),
};

// Acme Web Epics
export const acmeEpics: Epic[] = [
  {
    id: "epic-1",
    title: "User Management System",
    description: "Complete user authentication, authorization, and profile management system",
    projectId: "acme-web",
    status: "in-progress",
    priority: "high",
    progress: 65,
    color: "#3B82F6", // blue
    createdAt: new Date("2025-09-05"),
  },
  {
    id: "epic-2",
    title: "E-Commerce Integration",
    description: "Full e-commerce capabilities including shopping cart, checkout, and payment processing",
    projectId: "acme-web",
    status: "in-progress",
    priority: "high",
    progress: 40,
    color: "#10B981", // green
    createdAt: new Date("2025-09-10"),
  },
  {
    id: "epic-3",
    title: "Analytics & Reporting Dashboard",
    description: "Real-time analytics, custom reports, and data visualization tools",
    projectId: "acme-web",
    status: "planning",
    priority: "medium",
    progress: 15,
    color: "#8B5CF6", // purple
    createdAt: new Date("2025-09-15"),
  },
  {
    id: "epic-4",
    title: "Mobile Responsive Design",
    description: "Mobile-first responsive design across all platform features",
    projectId: "acme-web",
    status: "in-progress",
    priority: "high",
    progress: 55,
    color: "#F59E0B", // amber
    createdAt: new Date("2025-09-08"),
  },
  {
    id: "epic-5",
    title: "API & Third-Party Integrations",
    description: "RESTful API development and integration with external services",
    projectId: "acme-web",
    status: "planning",
    priority: "medium",
    progress: 20,
    color: "#EF4444", // red
    createdAt: new Date("2025-09-20"),
  },
];

// Acme Web Sprints
export const acmeSprints: Sprint[] = [
  {
    id: "acme-sprint-1",
    name: "Sprint 1 - Foundation",
    startDate: new Date("2025-09-02"),
    endDate: new Date("2025-09-16"),
    projectId: "acme-web",
    status: "completed",
  },
  {
    id: "acme-sprint-2",
    name: "Sprint 2 - Authentication",
    startDate: new Date("2025-09-16"),
    endDate: new Date("2025-09-30"),
    projectId: "acme-web",
    status: "completed",
  },
  {
    id: "acme-sprint-3",
    name: "Sprint 3 - Core Features",
    startDate: new Date("2025-09-30"),
    endDate: new Date("2025-10-14"),
    projectId: "acme-web",
    status: "completed",
  },
  {
    id: "acme-sprint-4",
    name: "Sprint 4 - E-Commerce",
    startDate: new Date("2025-10-14"),
    endDate: new Date("2025-10-28"),
    projectId: "acme-web",
    status: "active",
  },
  {
    id: "acme-sprint-5",
    name: "Sprint 5 - Polish & Testing",
    startDate: new Date("2025-10-28"),
    endDate: new Date("2025-11-11"),
    projectId: "acme-web",
    status: "planning",
  },
];

// Acme Web User Stories
export const acmeUserStories: UserStory[] = [
  // Epic 1: User Management System
  {
    id: "acme-us-1",
    title: "User Registration & Email Verification",
    description: "As a new user, I want to register an account and verify my email address",
    points: 8,
    status: "done",
    priority: "high",
    assignedTo: acmeUsers[2],
    sprintId: "acme-sprint-2",
    projectId: "acme-web",
    tags: ["authentication", "epic-1"],
    createdAt: new Date("2025-09-06"),
  },
  {
    id: "acme-us-2",
    title: "User Login with OAuth",
    description: "As a user, I want to login using Google, Facebook, or GitHub OAuth",
    points: 13,
    status: "done",
    priority: "high",
    assignedTo: acmeUsers[3],
    sprintId: "acme-sprint-2",
    projectId: "acme-web",
    tags: ["authentication", "oauth", "epic-1"],
    createdAt: new Date("2025-09-07"),
  },
  {
    id: "acme-us-3",
    title: "User Profile Management",
    description: "As a user, I want to update my profile information and preferences",
    points: 5,
    status: "done",
    priority: "medium",
    assignedTo: acmeUsers[4],
    sprintId: "acme-sprint-3",
    projectId: "acme-web",
    tags: ["profile", "epic-1"],
    createdAt: new Date("2025-09-08"),
  },
  {
    id: "acme-us-4",
    title: "Role-Based Access Control",
    description: "As an admin, I want to manage user roles and permissions",
    points: 8,
    status: "in-progress",
    priority: "high",
    assignedTo: acmeUsers[5],
    sprintId: "acme-sprint-4",
    projectId: "acme-web",
    tags: ["security", "admin", "epic-1"],
    createdAt: new Date("2025-09-09"),
  },
  
  // Epic 2: E-Commerce Integration
  {
    id: "acme-us-5",
    title: "Product Catalog with Search & Filters",
    description: "As a customer, I want to browse products with search and filtering options",
    points: 13,
    status: "in-progress",
    priority: "high",
    assignedTo: acmeUsers[2],
    sprintId: "acme-sprint-4",
    projectId: "acme-web",
    tags: ["e-commerce", "search", "epic-2"],
    createdAt: new Date("2025-09-11"),
  },
  {
    id: "acme-us-6",
    title: "Shopping Cart Management",
    description: "As a customer, I want to add, remove, and update items in my cart",
    points: 8,
    status: "in-progress",
    priority: "high",
    assignedTo: acmeUsers[4],
    sprintId: "acme-sprint-4",
    projectId: "acme-web",
    tags: ["e-commerce", "cart", "epic-2"],
    createdAt: new Date("2025-09-12"),
  },
  {
    id: "acme-us-7",
    title: "Checkout & Payment Integration",
    description: "As a customer, I want to securely checkout and pay using Stripe",
    points: 21,
    status: "ready",
    priority: "high",
    assignedTo: acmeUsers[3],
    sprintId: "acme-sprint-4",
    projectId: "acme-web",
    tags: ["e-commerce", "payment", "stripe", "epic-2"],
    createdAt: new Date("2025-09-13"),
  },
  {
    id: "acme-us-8",
    title: "Order History & Tracking",
    description: "As a customer, I want to view my order history and track shipments",
    points: 8,
    status: "new",
    priority: "medium",
    projectId: "acme-web",
    tags: ["e-commerce", "orders", "epic-2"],
    createdAt: new Date("2025-09-14"),
  },
  
  // Epic 3: Analytics & Reporting
  {
    id: "acme-us-9",
    title: "Real-Time Analytics Dashboard",
    description: "As an admin, I want to view real-time metrics and KPIs",
    points: 13,
    status: "new",
    priority: "medium",
    projectId: "acme-web",
    tags: ["analytics", "dashboard", "epic-3"],
    createdAt: new Date("2025-09-16"),
  },
  {
    id: "acme-us-10",
    title: "Custom Report Builder",
    description: "As an admin, I want to create custom reports with various data points",
    points: 21,
    status: "new",
    priority: "low",
    projectId: "acme-web",
    tags: ["analytics", "reports", "epic-3"],
    createdAt: new Date("2025-09-17"),
  },
  
  // Epic 4: Mobile Responsive Design
  {
    id: "acme-us-11",
    title: "Mobile Navigation & Menu",
    description: "As a mobile user, I want an intuitive mobile navigation experience",
    points: 5,
    status: "done",
    priority: "high",
    assignedTo: acmeUsers[4],
    sprintId: "acme-sprint-3",
    projectId: "acme-web",
    tags: ["mobile", "ui", "epic-4"],
    createdAt: new Date("2025-09-18"),
  },
  {
    id: "acme-us-12",
    title: "Responsive Product Grid",
    description: "As a mobile user, I want to view products in a mobile-optimized grid",
    points: 8,
    status: "in-progress",
    priority: "high",
    assignedTo: acmeUsers[2],
    sprintId: "acme-sprint-4",
    projectId: "acme-web",
    tags: ["mobile", "ui", "e-commerce", "epic-4"],
    createdAt: new Date("2025-09-19"),
  },
  
  // Epic 5: API & Integrations
  {
    id: "acme-us-13",
    title: "RESTful API Documentation",
    description: "As a developer, I want comprehensive API documentation",
    points: 5,
    status: "new",
    priority: "medium",
    projectId: "acme-web",
    tags: ["api", "documentation", "epic-5"],
    createdAt: new Date("2025-09-21"),
  },
  {
    id: "acme-us-14",
    title: "Webhook System",
    description: "As a developer, I want to configure webhooks for external integrations",
    points: 13,
    status: "new",
    priority: "low",
    projectId: "acme-web",
    tags: ["api", "webhooks", "epic-5"],
    createdAt: new Date("2025-09-22"),
  },
];

// Acme Web Tasks
export const acmeTasks: Task[] = [
  // Tasks for User Registration
  {
    id: "acme-t-1",
    title: "Design registration form UI",
    description: "Create responsive registration form with validation",
    status: "done",
    priority: "high",
    assignedTo: acmeUsers[2],
    userStoryId: "acme-us-1",
    epicId: "epic-1",
    projectId: "acme-web",
    createdAt: new Date("2025-09-16"),
    dueDate: new Date("2025-09-20"),
    estimatedHours: 12,
    actualHours: 11,
    testCoverage: 90,
    testStatus: "passed",
  },
  {
    id: "acme-t-2",
    title: "Implement email verification API",
    description: "Build backend API for email verification flow",
    status: "done",
    priority: "high",
    assignedTo: acmeUsers[3],
    userStoryId: "acme-us-1",
    epicId: "epic-1",
    projectId: "acme-web",
    createdAt: new Date("2025-09-17"),
    dueDate: new Date("2025-09-22"),
    estimatedHours: 16,
    actualHours: 18,
    testCoverage: 88,
    testStatus: "passed",
  },
  {
    id: "acme-t-3",
    title: "Setup SendGrid for emails",
    description: "Configure SendGrid for transactional emails",
    status: "done",
    priority: "medium",
    assignedTo: acmeUsers[5],
    userStoryId: "acme-us-1",
    epicId: "epic-1",
    projectId: "acme-web",
    createdAt: new Date("2025-09-18"),
    dueDate: new Date("2025-09-21"),
    estimatedHours: 6,
    actualHours: 5,
    testCoverage: 75,
    testStatus: "passed",
  },
  
  // Tasks for OAuth Login
  {
    id: "acme-t-4",
    title: "Integrate Google OAuth",
    description: "Setup Google OAuth 2.0 authentication",
    status: "done",
    priority: "high",
    assignedTo: acmeUsers[3],
    userStoryId: "acme-us-2",
    epicId: "epic-1",
    projectId: "acme-web",
    createdAt: new Date("2025-09-19"),
    dueDate: new Date("2025-09-24"),
    estimatedHours: 12,
    actualHours: 14,
    testCoverage: 85,
    testStatus: "passed",
  },
  {
    id: "acme-t-5",
    title: "Integrate GitHub OAuth",
    description: "Setup GitHub OAuth authentication",
    status: "done",
    priority: "medium",
    assignedTo: acmeUsers[3],
    userStoryId: "acme-us-2",
    epicId: "epic-1",
    projectId: "acme-web",
    createdAt: new Date("2025-09-20"),
    dueDate: new Date("2025-09-25"),
    estimatedHours: 10,
    actualHours: 9,
    testCoverage: 82,
    testStatus: "passed",
  },
  
  // Tasks for Profile Management
  {
    id: "acme-t-6",
    title: "Build profile settings page",
    description: "Create UI for profile settings and preferences",
    status: "done",
    priority: "medium",
    assignedTo: acmeUsers[4],
    userStoryId: "acme-us-3",
    epicId: "epic-1",
    projectId: "acme-web",
    createdAt: new Date("2025-09-30"),
    dueDate: new Date("2025-10-05"),
    estimatedHours: 14,
    actualHours: 13,
    testCoverage: 80,
    testStatus: "passed",
  },
  {
    id: "acme-t-7",
    title: "Implement avatar upload",
    description: "Add avatar image upload with S3 storage",
    status: "done",
    priority: "low",
    assignedTo: acmeUsers[5],
    userStoryId: "acme-us-3",
    epicId: "epic-1",
    projectId: "acme-web",
    createdAt: new Date("2025-10-01"),
    dueDate: new Date("2025-10-06"),
    estimatedHours: 8,
    actualHours: 10,
    testCoverage: 78,
    testStatus: "passed",
  },
  
  // Tasks for RBAC
  {
    id: "acme-t-8",
    title: "Define permission schema",
    description: "Design role and permission data structure",
    status: "done",
    priority: "high",
    assignedTo: acmeUsers[5],
    userStoryId: "acme-us-4",
    epicId: "epic-1",
    projectId: "acme-web",
    createdAt: new Date("2025-10-14"),
    dueDate: new Date("2025-10-18"),
    estimatedHours: 8,
    actualHours: 7,
    testCoverage: 95,
    testStatus: "passed",
  },
  {
    id: "acme-t-9",
    title: "Build role management UI",
    description: "Create admin interface for managing roles",
    status: "code-review",
    priority: "high",
    assignedTo: acmeUsers[2],
    userStoryId: "acme-us-4",
    epicId: "epic-1",
    projectId: "acme-web",
    createdAt: new Date("2025-10-15"),
    dueDate: new Date("2025-10-22"),
    estimatedHours: 16,
    actualHours: 14,
    testCoverage: 82,
    testStatus: "passed",
  },
  {
    id: "acme-t-10",
    title: "Implement permission middleware",
    description: "Add middleware for checking user permissions",
    status: "testing",
    priority: "high",
    assignedTo: acmeUsers[5],
    userStoryId: "acme-us-4",
    epicId: "epic-1",
    projectId: "acme-web",
    createdAt: new Date("2025-10-16"),
    dueDate: new Date("2025-10-23"),
    estimatedHours: 12,
    actualHours: 15,
    testCoverage: 88,
    testStatus: "in-progress",
  },
  
  // Tasks for Product Catalog
  {
    id: "acme-t-11",
    title: "Design product listing page",
    description: "Create responsive product grid with filters",
    status: "in-progress",
    priority: "high",
    assignedTo: acmeUsers[4],
    userStoryId: "acme-us-5",
    epicId: "epic-2",
    projectId: "acme-web",
    createdAt: new Date("2025-10-15"),
    dueDate: new Date("2025-10-20"),
    estimatedHours: 20,
    actualHours: 18,
    testCoverage: 65,
    testStatus: "in-progress",
  },
  {
    id: "acme-t-12",
    title: "Implement Elasticsearch integration",
    description: "Setup Elasticsearch for product search",
    status: "in-progress",
    priority: "critical",
    assignedTo: acmeUsers[3],
    userStoryId: "acme-us-5",
    epicId: "epic-2",
    projectId: "acme-web",
    createdAt: new Date("2025-10-16"),
    dueDate: new Date("2025-10-24"),
    estimatedHours: 24,
    actualHours: 30,
    testCoverage: 45,
    testStatus: "not-started",
    isBlocked: true,
    blockedReason: "Waiting for DevOps to provision Elasticsearch cluster",
  },
  {
    id: "acme-t-13",
    title: "Add faceted search filters",
    description: "Implement category, price, and rating filters",
    status: "todo",
    priority: "medium",
    assignedTo: acmeUsers[2],
    userStoryId: "acme-us-5",
    epicId: "epic-2",
    projectId: "acme-web",
    createdAt: new Date("2025-10-17"),
    dueDate: new Date("2025-10-25"),
    estimatedHours: 12,
    testCoverage: 0,
    testStatus: "not-started",
  },
  
  // Tasks for Shopping Cart
  {
    id: "acme-t-14",
    title: "Design cart UI component",
    description: "Create cart sidebar with item management",
    status: "code-review",
    priority: "high",
    assignedTo: acmeUsers[4],
    userStoryId: "acme-us-6",
    epicId: "epic-2",
    projectId: "acme-web",
    createdAt: new Date("2025-10-18"),
    dueDate: new Date("2025-10-22"),
    estimatedHours: 16,
    actualHours: 16,
    testCoverage: 78,
    testStatus: "passed",
  },
  {
    id: "acme-t-15",
    title: "Implement cart state management",
    description: "Setup Redux for cart state",
    status: "in-progress",
    priority: "high",
    assignedTo: acmeUsers[2],
    userStoryId: "acme-us-6",
    epicId: "epic-2",
    projectId: "acme-web",
    createdAt: new Date("2025-10-19"),
    dueDate: new Date("2025-10-23"),
    estimatedHours: 12,
    actualHours: 10,
    testCoverage: 55,
    testStatus: "in-progress",
  },
  {
    id: "acme-t-16",
    title: "Add cart persistence",
    description: "Save cart to localStorage and database",
    status: "todo",
    priority: "medium",
    assignedTo: acmeUsers[5],
    userStoryId: "acme-us-6",
    epicId: "epic-2",
    projectId: "acme-web",
    createdAt: new Date("2025-10-20"),
    dueDate: new Date("2025-10-24"),
    estimatedHours: 8,
    testCoverage: 0,
    testStatus: "not-started",
  },
  
  // Tasks for Checkout & Payment
  {
    id: "acme-t-17",
    title: "Design checkout flow",
    description: "Create multi-step checkout process",
    status: "testing",
    priority: "high",
    assignedTo: acmeUsers[4],
    userStoryId: "acme-us-7",
    epicId: "epic-2",
    projectId: "acme-web",
    createdAt: new Date("2025-10-14"),
    dueDate: new Date("2025-10-19"),
    estimatedHours: 20,
    actualHours: 22,
    testCoverage: 90,
    testStatus: "in-progress",
  },
  {
    id: "acme-t-18",
    title: "Integrate Stripe Payment",
    description: "Setup Stripe for payment processing",
    status: "testing",
    priority: "critical",
    assignedTo: acmeUsers[3],
    userStoryId: "acme-us-7",
    epicId: "epic-2",
    projectId: "acme-web",
    createdAt: new Date("2025-10-15"),
    dueDate: new Date("2025-10-21"),
    estimatedHours: 16,
    actualHours: 18,
    testCoverage: 85,
    testStatus: "failed",
    isBlocked: true,
    blockedReason: "Stripe webhook validation failing intermittently",
  },
  {
    id: "acme-t-19",
    title: "Add order confirmation email",
    description: "Send email confirmation after successful order",
    status: "todo",
    priority: "medium",
    assignedTo: acmeUsers[5],
    userStoryId: "acme-us-7",
    epicId: "epic-2",
    projectId: "acme-web",
    createdAt: new Date("2025-10-16"),
    dueDate: new Date("2025-10-22"),
    estimatedHours: 6,
    testCoverage: 0,
    testStatus: "not-started",
  },
  
  // Tasks for Mobile Navigation
  {
    id: "acme-t-20",
    title: "Build hamburger menu",
    description: "Create responsive mobile navigation menu",
    status: "done",
    priority: "high",
    assignedTo: acmeUsers[4],
    userStoryId: "acme-us-11",
    epicId: "epic-4",
    projectId: "acme-web",
    createdAt: new Date("2025-10-01"),
    dueDate: new Date("2025-10-05"),
    estimatedHours: 8,
    actualHours: 7,
    testCoverage: 85,
    testStatus: "passed",
  },
  {
    id: "acme-t-21",
    title: "Add mobile gestures",
    description: "Implement swipe gestures for navigation",
    status: "done",
    priority: "medium",
    assignedTo: acmeUsers[2],
    userStoryId: "acme-us-11",
    epicId: "epic-4",
    projectId: "acme-web",
    createdAt: new Date("2025-10-02"),
    dueDate: new Date("2025-10-06"),
    estimatedHours: 6,
    actualHours: 8,
    testCoverage: 80,
    testStatus: "passed",
  },
  
  // Tasks for Responsive Product Grid
  {
    id: "acme-t-22",
    title: "Optimize product card for mobile",
    description: "Make product cards mobile-friendly",
    status: "in-progress",
    priority: "high",
    assignedTo: acmeUsers[4],
    userStoryId: "acme-us-12",
    epicId: "epic-4",
    projectId: "acme-web",
    createdAt: new Date("2025-10-17"),
    dueDate: new Date("2025-10-21"),
    estimatedHours: 10,
    actualHours: 8,
    testCoverage: 70,
    testStatus: "in-progress",
  },
  {
    id: "acme-t-23",
    title: "Add infinite scroll",
    description: "Implement infinite scroll for product listing",
    status: "todo",
    priority: "medium",
    assignedTo: acmeUsers[2],
    userStoryId: "acme-us-12",
    epicId: "epic-4",
    projectId: "acme-web",
    createdAt: new Date("2025-10-18"),
    dueDate: new Date("2025-10-24"),
    estimatedHours: 8,
    testCoverage: 0,
    testStatus: "not-started",
  },
  {
    id: "acme-t-24",
    title: "Update API rate limiting logic",
    description: "Implement proper rate limiting for API endpoints",
    status: "done",
    priority: "high",
    assignedTo: acmeUsers[3],
    epicId: "epic-5",
    projectId: "acme-web",
    createdAt: new Date("2025-10-10"),
    dueDate: new Date("2025-10-14"),
    estimatedHours: 8,
    actualHours: 9,
    testCoverage: 92,
    testStatus: "passed",
  },
  {
    id: "acme-t-25",
    title: "Create API documentation portal",
    description: "Build interactive API docs with Swagger",
    status: "code-review",
    priority: "medium",
    assignedTo: acmeUsers[5],
    epicId: "epic-5",
    projectId: "acme-web",
    createdAt: new Date("2025-10-18"),
    dueDate: new Date("2025-10-24"),
    estimatedHours: 12,
    actualHours: 11,
    testCoverage: 60,
    testStatus: "passed",
  },
  {
    id: "acme-t-26",
    title: "Analytics event tracking setup",
    description: "Implement event tracking system for analytics",
    status: "todo",
    priority: "medium",
    assignedTo: acmeUsers[2],
    epicId: "epic-3",
    projectId: "acme-web",
    createdAt: new Date("2025-10-20"),
    dueDate: new Date("2025-10-27"),
    estimatedHours: 16,
    testCoverage: 0,
    testStatus: "not-started",
  },
];

// Acme Web Issues
export const acmeIssues: Issue[] = [
  {
    id: "acme-i-1",
    title: "OAuth redirect fails on Safari",
    description: "GitHub OAuth redirect doesn't work properly on Safari browser",
    type: "bug",
    severity: "important",
    priority: "high",
    status: "in-progress",
    assignedTo: acmeUsers[3],
    projectId: "acme-web",
    createdAt: new Date("2025-10-18"),
  },
  {
    id: "acme-i-2",
    title: "Cart icon doesn't update immediately",
    description: "Cart badge count doesn't update until page refresh",
    type: "bug",
    severity: "normal",
    priority: "medium",
    status: "new",
    assignedTo: acmeUsers[2],
    projectId: "acme-web",
    createdAt: new Date("2025-10-19"),
  },
  {
    id: "acme-i-3",
    title: "Add export to CSV functionality",
    description: "Users need ability to export order history to CSV",
    type: "enhancement",
    severity: "normal",
    priority: "low",
    status: "new",
    projectId: "acme-web",
    createdAt: new Date("2025-10-20"),
  },
  {
    id: "acme-i-4",
    title: "Password reset email delay",
    description: "Password reset emails taking 5-10 minutes to arrive",
    type: "bug",
    severity: "important",
    priority: "high",
    status: "in-progress",
    assignedTo: acmeUsers[5],
    projectId: "acme-web",
    createdAt: new Date("2025-10-21"),
  },
  {
    id: "acme-i-5",
    title: "How to implement custom webhooks?",
    description: "Need documentation on webhook implementation",
    type: "question",
    severity: "minor",
    priority: "low",
    status: "new",
    projectId: "acme-web",
    createdAt: new Date("2025-10-22"),
  },
  {
    id: "acme-i-6",
    title: "Product images load slowly on mobile",
    description: "Need to implement lazy loading for product images",
    type: "enhancement",
    severity: "normal",
    priority: "medium",
    status: "new",
    projectId: "acme-web",
    createdAt: new Date("2025-10-23"),
  },
];
