import type { User, Project, Sprint, UserStory, Task, Issue, Epic } from "../types";
import {
  acmeProject,
  acmeUsers,
  acmeSprints,
  acmeUserStories,
  acmeTasks,
  acmeIssues,
  acmeEpics,
} from "./acme-web-data";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    avatar: "https://images.unsplash.com/photo-1748256622734-92241ae7b43f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWFtJTIwY29sbGFib3JhdGlvbiUyMHdvcmtzcGFjZXxlbnwxfHx8fDE3NjEzODAwNTF8MA&ixlib=rb-4.1.0&q=80&w=400",
    role: "Product Owner",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael@example.com",
    avatar: "https://images.unsplash.com/photo-1735639013995-086e648eaa38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9qZWN0JTIwcGxhbm5pbmclMjBvZmZpY2V8ZW58MXx8fHwxNzYxNDg4MDg4fDA&ixlib=rb-4.1.0&q=80&w=400",
    role: "Scrum Master",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily@example.com",
    avatar: "https://images.unsplash.com/photo-1624555130296-e551faf8969b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkaXZlcnNlJTIwdGVhbSUyMG1lZXRpbmd8ZW58MXx8fHwxNzYxNDgzNTkwfDA&ixlib=rb-4.1.0&q=80&w=400",
    role: "Developer",
  },
  {
    id: "4",
    name: "David Kim",
    email: "david@example.com",
    role: "Developer",
  },
  {
    id: "5",
    name: "Alex Thompson",
    email: "alex@example.com",
    role: "QA",
  },
];

export const mockProjects: Project[] = [
  acmeProject, // Acme Web - Feature project with full seeded data
  {
    id: "1",
    name: "Mobile App Redesign",
    description: "Complete redesign of the mobile application with new features",
    color: "#3B82F6",
    members: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[4]],
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "E-Commerce Platform",
    description: "Building a scalable e-commerce solution",
    color: "#10B981",
    members: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[3]],
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    name: "Analytics Dashboard",
    description: "Real-time analytics and reporting dashboard",
    color: "#F59E0B",
    members: [mockUsers[1], mockUsers[2], mockUsers[3]],
    createdAt: new Date("2024-03-10"),
  },
];

export const mockSprints: Sprint[] = [
  ...acmeSprints,
  {
    id: "1",
    name: "Sprint 23 - Q4 Goals",
    startDate: new Date("2025-10-20"),
    endDate: new Date("2025-11-03"),
    projectId: "1",
    status: "active",
  },
  {
    id: "2",
    name: "Sprint 24 - Feature Release",
    startDate: new Date("2025-11-04"),
    endDate: new Date("2025-11-18"),
    projectId: "1",
    status: "planning",
  },
];

export const mockUserStories: UserStory[] = [
  ...acmeUserStories,
  {
    id: "us-1",
    title: "User Authentication Flow",
    description: "As a user, I want to securely log in to the application using email and password",
    points: 8,
    status: "in-progress",
    priority: "high",
    assignedTo: mockUsers[2],
    sprintId: "1",
    projectId: "1",
    tags: ["authentication", "security"],
    createdAt: new Date("2025-10-15"),
  },
  {
    id: "us-2",
    title: "Dashboard Analytics",
    description: "As an admin, I want to view real-time analytics on the dashboard",
    points: 13,
    status: "ready",
    priority: "medium",
    assignedTo: mockUsers[3],
    sprintId: "1",
    projectId: "1",
    tags: ["analytics", "dashboard"],
    createdAt: new Date("2025-10-16"),
  },
  {
    id: "us-3",
    title: "Payment Integration",
    description: "As a user, I want to make secure payments using multiple payment methods",
    points: 21,
    status: "new",
    priority: "high",
    projectId: "1",
    tags: ["payment", "integration"],
    createdAt: new Date("2025-10-18"),
  },
  {
    id: "us-4",
    title: "Notification System",
    description: "As a user, I want to receive notifications for important updates",
    points: 5,
    status: "done",
    priority: "medium",
    assignedTo: mockUsers[2],
    sprintId: "1",
    projectId: "1",
    tags: ["notifications"],
    createdAt: new Date("2025-10-10"),
  },
];

export const mockTasks: Task[] = [
  ...acmeTasks,
  {
    id: "t-1",
    title: "Design login screen mockups",
    description: "Create high-fidelity mockups for the login screen",
    status: "done",
    priority: "high",
    assignedTo: mockUsers[4],
    userStoryId: "us-1",
    projectId: "1",
    createdAt: new Date("2025-10-15"),
    dueDate: new Date("2025-10-25"),
  },
  {
    id: "t-2",
    title: "Implement JWT authentication",
    description: "Set up JWT token-based authentication system",
    status: "in-progress",
    priority: "high",
    assignedTo: mockUsers[2],
    userStoryId: "us-1",
    projectId: "1",
    createdAt: new Date("2025-10-16"),
    dueDate: new Date("2025-10-28"),
  },
  {
    id: "t-3",
    title: "Create password reset flow",
    description: "Implement forgot password and reset functionality",
    status: "todo",
    priority: "medium",
    assignedTo: mockUsers[2],
    userStoryId: "us-1",
    projectId: "1",
    createdAt: new Date("2025-10-17"),
    dueDate: new Date("2025-10-30"),
  },
  {
    id: "t-4",
    title: "Set up analytics tracking",
    description: "Integrate analytics tracking library",
    status: "testing",
    priority: "medium",
    assignedTo: mockUsers[3],
    userStoryId: "us-2",
    projectId: "1",
    createdAt: new Date("2025-10-18"),
    dueDate: new Date("2025-10-27"),
  },
  {
    id: "t-5",
    title: "Design dashboard charts",
    description: "Create interactive charts for dashboard",
    status: "in-progress",
    priority: "medium",
    assignedTo: mockUsers[4],
    userStoryId: "us-2",
    projectId: "1",
    createdAt: new Date("2025-10-19"),
    dueDate: new Date("2025-10-29"),
  },
  {
    id: "t-6",
    title: "Research payment gateways",
    description: "Research and compare different payment gateway options",
    status: "todo",
    priority: "high",
    userStoryId: "us-3",
    projectId: "1",
    createdAt: new Date("2025-10-20"),
  },
];

export const mockIssues: Issue[] = [
  ...acmeIssues,
  {
    id: "i-1",
    title: "Login button not responding on mobile",
    description: "The login button doesn't work on iOS Safari",
    type: "bug",
    severity: "important",
    priority: "high",
    status: "in-progress",
    assignedTo: mockUsers[2],
    projectId: "1",
    createdAt: new Date("2025-10-22"),
  },
  {
    id: "i-2",
    title: "Add dark mode support",
    description: "Users are requesting a dark mode option",
    type: "enhancement",
    severity: "normal",
    priority: "medium",
    status: "new",
    projectId: "1",
    createdAt: new Date("2025-10-23"),
  },
  {
    id: "i-3",
    title: "How to export data?",
    description: "Need clarification on data export functionality",
    type: "question",
    severity: "minor",
    priority: "low",
    status: "done",
    assignedTo: mockUsers[0],
    projectId: "1",
    createdAt: new Date("2025-10-20"),
  },
];

export const mockEpics: Epic[] = [...acmeEpics];
